# Generated by Django 5.2 on 2025-04-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_vagas', '0002_rename_nome_vagas_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=12)),
                ('cpf', models.IntegerField(max_length=11)),
            ],
        ),
    ]
